[package]
name = "commonlib-rs"
version = "0.0.1"
edition = "2021"

[dependencies]
chrono = "0.4.33"
env_logger = "0.11.1"
log = "0.4.20"
owo-colors = "4.0.0"
supports-color = "3.0.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[profile.release]
opt-level = 3
