[package]
name = "test-app"
version = "0.0.0"
edition = "2021"

[dependencies]
async-std = {version = "1.12.0", features = ["attributes"]}
commonlib = { version = "0.0.1", path = "..", features = ["logger"] }
tokio = "1.36.0"
tracing = "0.1.40"

[profile.release]
opt-level = 3
